/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package midterm;
import java.util.Random;

/**
 *
 * @author taron
 */
public class MidtermGUI extends javax.swing.JFrame {

    /**
     * Creates new form MidtermGUI
     */
    
    int lotteryNumbers[] = new int[18];   // winning numbers
    int winningBonus;                     // bonus number

    int take3[] = new int[3];             
    int bonus3;                           
    int take4[] = new int[4];             
    int bonus4;                           
    int take5[] = new int[5];             
    int bonus5;                           
    
    Random rand = new Random(); 
    boolean ticketsGenerated = false;
    boolean resultsPrinted = false;
    
    public MidtermGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        start = new javax.swing.JButton();
        display = new javax.swing.JButton();
        results = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lottery Game");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        display.setText("Display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        results.setText("Results");
        results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(start)
                        .addGap(18, 18, 18)
                        .addComponent(display)
                        .addGap(18, 18, 18)
                        .addComponent(results)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(display)
                    .addComponent(results))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        // don't regenerate
        if (ticketsGenerated) return; 
        ticketsGenerated = true;

        // Generate Take 3 numbers + bonus
        for (int i = 0; i < 3; i++) {
            take3[i] = rand.nextInt(64) + 1;
        }
        bonus3 = rand.nextInt(64) + 1;

        // Generate Take 4 numbers + bonus
        for (int i = 0; i < 4; i++) {
            take4[i] = rand.nextInt(64) + 1;
        }
        bonus4 = rand.nextInt(64) + 1;

        // Generate Take 5 numbers + bonus
        for (int i = 0; i < 5; i++) {
            take5[i] = rand.nextInt(64) + 1;
        }
        bonus5 = rand.nextInt(64) + 1;

        // Display the tickets
        jTextArea1.append("\nTake 3: ");
        for (int i = 0; i < take3.length; i++) {
            jTextArea1.append(take3[i] + " ");
        }
        jTextArea1.append("| Bonus: " + bonus3 + "\n");

        jTextArea1.append("Take 4: ");
        for (int i = 0; i < take4.length; i++) {
            jTextArea1.append(take4[i] + " ");
        };
        jTextArea1.append("| Bonus: " + bonus4 + "\n");

        jTextArea1.append("Take 5: ");
        for (int i = 0; i < take5.length; i++) {
            jTextArea1.append(take5[i] + " ");
        }
        jTextArea1.append("| Bonus: " + bonus5 + "\n");
    }//GEN-LAST:event_displayActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        // clear previous output
        jTextArea1.setText("");
        

        Random rand = new Random();

        // generate 18 lottery numbers
        for (int i = 0; i < 18; i++) {
            lotteryNumbers[i] = rand.nextInt(64) + 1;
            jTextArea1.append(lotteryNumbers[i] + " ");
        }

        // generate the bonus number for the lottery
        winningBonus = rand.nextInt(64) + 1;
        jTextArea1.append("\n");
        jTextArea1.append("Winning Bonus: " + winningBonus + "\n");
        
        resultsPrinted = false;
        ticketsGenerated = false;
        
    }//GEN-LAST:event_startActionPerformed
    
    private void checkTicketResult(String label, int[] ticket, int ticketBonus, int basePrize) {
    int matchCount = 0;

    // count how many numbers matched the lottery numbers
    for (int i = 0; i < ticket.length; i++) {
        for (int j = 0; j < lotteryNumbers.length; j++) {
            if (ticket[i] == lotteryNumbers[j]) {
                matchCount++;
                break;
            }
        }
    }

    // WIN if all numbers match
    if (matchCount == ticket.length) {
        int prize = basePrize;
        if (ticketBonus == winningBonus) {
            prize *= 10;
            jTextArea1.append(label + ": WIN (Matched " + matchCount + " with bonus) = $" + prize + "\n");
        } else {
            jTextArea1.append(label + ": WIN (Matched " + matchCount + ") = $" + prize + "\n");
        }
    } 
    // LOSE if not all numbers match
    else {
        jTextArea1.append(label + ": LOSE (Matched " + matchCount + ") = $0\n");
    }
}
    
    private void resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsActionPerformed
        // TODO add your handling code here:
        if (!ticketsGenerated) {
            jTextArea1.append("\nPlease click Display first.\n");
            return;
        }
        // If results already printed, do nothing
        if (resultsPrinted) return;
        jTextArea1.append("\n");
        // Check Take 3
        checkTicketResult("Take 3", take3, bonus3, 1000);

        // Check Take 4
        checkTicketResult("Take 4", take4, bonus4, 10000);

        // Check Take 5
        checkTicketResult("Take 5", take5, bonus5, 100000);
        
        resultsPrinted = true;
    }//GEN-LAST:event_resultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MidtermGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton display;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton results;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
